[package]
name = "wks-client-responder"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
email_address = "0.2.4"
pgp = "0.11.0"
