name: Build
on:
  pull_request:
  push:
    branches:
      - "**"
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      release:
        required: false
        type: boolean

permissions:
  contents: read
  actions: write

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default ref
        if: ${{ inputs.ref == '' }}
        uses: actions/checkout@v4.1.1
      - name: Checkout requested ref
        if: ${{ inputs.ref != '' }}
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Rust
        run: |
          rustup target add ${{ matrix.target }}
      - uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --release --target ${{ matrix.target }}
      - run: tar -czf wks-client-responder_release.tar.gz target/release/wks-client-responder
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ matrix.target }}
          path: wks-client-responder_${{ matrix.target }}_release.tar.gz
