name: Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions:
  contents: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref }}
    permissions:
      contents: read
      actions: write
  publish_github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
      - uses: actions/download-artifact@v4.1.2
      - name: Determine release type
        id: release_type
        run: |
          if [[ ${{ github.ref_name }} == *-alpha ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref_name }} == *-beta ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Get release notes
        id: notes
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          git tag -l --format='%(contents:body)' ${{ github.ref_name }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash
      - uses: softprops/action-gh-release@v0.1.15
        with:
          body: ${{ steps.notes.outputs.content }}
          draft: false
          prerelease: ${{ steps.release_type.outputs.prerelease }}
          files: wks-client-responder_*_release.tar.gz
          name: wks-client-responder ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: false
          generate_release_notes: false
          append_body: false
